title: Zoe's blog
author: Yang Yang
email: yyoung_11@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome everyone! Here's my new blog site. 

# social links
twitter_username: yyoung_11
github_username:  heyyoulisten

show_excerpts: true # set to false to remove excerpts on the homepage
